# Generated by Django 5.1.2 on 2024-10-20 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('guest_adult', models.IntegerField()),
                ('guest_children', models.IntegerField()),
                ('image', models.ImageField(upload_to='rooms/')),
                ('price', models.IntegerField()),
                ('amenities', models.ManyToManyField(to='rooms.roomamenity')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, unique=True)),
                ('availability', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('DIRTY', 'Dirty')], default='VACANT', max_length=8)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.roomtype')),
            ],
        ),
    ]
